name: Cache Priming Workflow

on: [push, workflow_dispatch]

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Dummy Dependencies
        run: |
          mkdir -p .my-cache
          echo "Simulating dependency data..." > .my-cache/data.txt

      - name: Restore Cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: .my-cache
          key: cache-b8f30a0

      - name: prime-cache-b8f30a0
        run: echo "Cache Hit Status ${{ steps.cache-step.outputs.cache-hit }}"